.ds ]W %
.ds ]L
.nh
.TH post 1 "OpenLava Version 3.0 - Apr 2015"
.br
.SH NAME
\fBbpost\fR - sends message to a job
.SH SYNOPSIS
.BR
.PP
.PP
\fBbpost\fR\fB \fR\f \fR-d "message"\fR   \fR\fIjob_ID\fR
.PP
\fBbpost\fR\fB \fR[\fB-h\fR | \fB-V\fR]
.SH DESCRIPTION
.BR
.PP
.PP
Allow users to post messages to their own jobs. Messages can be posted until
the job is cleaned from OpenLava. There is no limit to the number of messages
that can be posted to a job, however the size of each individual message cannot
exceed 1K.
\fB\f

.SH OPTIONS
.BR
.PP
.TP
 \fIjob_ID\fR | \fB"\fR\fIjob_ID\fR\fB[\fR\fIindex_list\fR\fB]"
\fR
.IP
Required. Job ID of the job or of the job array on which to operate.

.IP
For a job array, the index list, the square brackets, and the quotation
marks are required. An index list is used to operate on a job array.
.TP
\fB-d
\fR
.IP
The message to be posted to a job
.TP
\fB-h
\fR
.IP
Prints command usage to stderr and exit.

.TP
\fB-V
\fR
.IP
Prints openlava release version to stderr and exit.

.SH EXAMPLE
.BR
.PP
.TP
$bpost -d "message in a bottle" 7249
.PP
Message to job 7249 posted all right.

.SH SEE ALSO
.BR
.PP
.PP
bread(1), bjobs(1)
