.ds ]W %
.ds ]L
.nh
.TH bresources 1 "OpenLava Version 4.0 - Aug 2016"
.br
.SH NAME
\fBbresources\fR - displays information about resource limits of running jobs
.SH SYNOPSIS
.BR
.PP
.PP
\fBbresources\fR [\fB-h\fR | \fB-V\fR] 
.SH DESCRIPTION
.BR
.PP
.PP
Displays resource limit information.
.PP
.SH OPTIONS
.BR
.PP
.TP
\fB-h
\fR
.IP
Prints command usage to stderr and exits. 


.TP
\fB-V
\fR
.IP
Prints OpenLava release version to stderr and exits. 
.PP
.SH DEFAULT OUTPUT
.BR
.PP
Current usage of resource limits are displayed with the following fields:
.PP
\fBLIMIT\fR
.IP
The name of the resource limit.
.PP
\fBQUEUES or PER_QUEUE\fR
.IP
Queues defined in lsb.resources.
.PP
\fBHOSTS or PER_HOST\fR
.IP
Hosts or host groups defined in lsb.resources.
.PP
\fBPROJECTS or PER_PROJECT\fR
.IP
Projects defined in lsb.resources.
.PP
\fBUSERS or PER_USER\fR
.IP
Users or user groups defined in lsb.resources.
.PP
\fBexpand\fR
.IP
Expanded values of consumer. 
If a user group or host group is used in consumer definition, all members are displayed.
If a group contains a subgroup, each member in the subgroup is displayed recursively.
If not operator (~) is used in consumer definition, all members exclude specified
host/user/queue/project are displayed.
.PP
\fBCURRENT LIMIT RESOURCE USAGE\fR
.IP
Current resrouce usage of projects on this limit.
.PP
\fBPROJECT\fR
.IP
Project defined in this limit has started jobs.
.PP
\fBQUEUE\fR
.IP
The jobs are started on the queue.
.PP
\fBUSER\fR
.IP
The jobs are submitted by the user.
.PP
\fBHOST\fR
.IP
The jobs are running on the host.
.PP
\fBSLOTS\fR
.IP
The number of used slots and the maximum number of slots this project/user/host/queue can start.
.PP
\fBJOBS\fR
.IP
The number of started jobs and the maximum number of jobs this project/user/host/queue can start.
.PP
.SH EXAMPLE
.PP
bresources
.PP
LIMIT  Limit1
.br
HOSTS      : all ~grp1
.br
    expand : host3 host4
.br
USERS      : all ~openlava
.br
    expand : david wlu
.br
SLOTS      : 0
.br
.PP
LIMIT  Limit2
.br
QUEUES     : normal
.br
    expand : normal
.br
PROJECTS   : Proj1 Proj2 Proj3
.br
JOBS       : 10
.br
CURRENT LIMIT RESOURCE USAGE:
.br
    PROJECT     QUEUE       JOBS
.br
    Proj1       normal      5/10
    Proj2       nornal      2/10
.br
.PP
LIMIT  jenkinslimits
.br
QUEUES     : normal owner
.br
    expand : normal owner
.br
PER_USER   : G1
.br
    expand : david wlu james john
.br
SLOTS      : 20 09:00-17:00
.br
SLOTS      : 10 17:00-09:00
.br
CURRENT LIMIT RESOURCE USAGE:
.br
    PROJECT     QUEUE       USER        HOST        SLOTS       JOBS
.br
    -           owner       john       -           5/10        -
.br
    -           normal      john       -           5/10        -
.PP
.SH SEE ALSO
.BR
.PP
.PP
busers(1), bqueues(1), bhosts(1)
