.ds ]W %
.ds ]L
.nh
.TH bresources 1 "OpenLava Version 3.3 - Mar 2016"
.br
.SH NAME
\fBbresources\fR - displays information about resource limits
.SH SYNOPSIS
.BR
.PP
.PP
\fBbresources\fR [\fB-h\fR | \fB-V\fR] 
.SH DESCRIPTION
.BR
.PP
.PP
Displays resource limit information.
.PP
.SH OPTIONS
.BR
.PP
.TP
\fB-h
\fR
.IP
Prints command usage to stderr and exits. 


.TP
\fB-V
\fR
.IP
Prints OpenLava release version to stderr and exits. 
.PP
.SH DEFAULT OUTPUT
.BR
.PP
A list of resource limits is displayed with the following fields:
.PP
\fBLIMIT\fR
.IP
The name of the resource limit.
.PP
\fBQUEUES\fR
.IP
Queues defined in lsb.resources.
.PP
\fBHOSTS\fR
.IP
Hosts or host groups defined in lsb.resources.
.PP
\fBPROJECTS\fR
.IP
Projects defined in lsb.resources.
.PP
\fBUSERS\fR
.IP
Users or user groups defined in lsb.resources.
.PP
\fBexpand\fR
.IP
Expanded values of consumer. 
If a user group or host group is used in consumer definition, all members are displayed.
If a group contains a subgroup, each member in the subgroup is displayed recursively.
If not operator (~) is used in consumer definition, all members exclude specified
host/user/queue/project are displayed.
.PP
.SH EXAMPLE
.PP
bresources
.PP
LIMIT  Limit1
.br
HOSTS      : all ~grp1
.br
    expand : host3 host4
.br
USERS      : all ~openlava
.br
    expand : david wlu
.br
SLOTS      : 0

.PP
.SH SEE ALSO
.BR
.PP
.PP
busers(1), bqueues(1), bhosts(1)
